program: sweep_train.py
method: grid
metric:
  name: episode/total_reward
  goal: maximize
parameters:
  combo:
    values:
    - run_group: full_soft_noPred
      full_rewards: false
      action_delay: 3
      predict: false
      target_update: soft
      dueling: true
      noisy: true
      distributional: true
      nstep: 3
    - run_group: full_soft_pred
      full_rewards: false
      action_delay: 3
      predict: true
      target_update: soft
      dueling: true
      noisy: true
      distributional: true
      nstep: 3
    - run_group: no_dueling_soft_noPred
      full_rewards: false
      action_delay: 3
      predict: false
      target_update: soft
      dueling: false
      noisy: true
      distributional: true
      nstep: 3
    - run_group: no_dueling_soft_pred
      full_rewards: false
      action_delay: 3
      predict: true
      target_update: soft
      dueling: false
      noisy: true
      distributional: true
      nstep: 3
    - run_group: no_noisy_soft_noPred
      full_rewards: false
      action_delay: 3
      predict: false
      target_update: soft
      dueling: true
      noisy: false
      distributional: true
      nstep: 3
    - run_group: no_noisy_soft_pred
      full_rewards: false
      action_delay: 3
      predict: true
      target_update: soft
      dueling: true
      noisy: false
      distributional: true
      nstep: 3
    - run_group: no_distributional_soft_noPred
      full_rewards: false
      action_delay: 3
      predict: false
      target_update: soft
      dueling: true
      noisy: true
      distributional: false
      nstep: 3
    - run_group: no_distributional_soft_pred
      full_rewards: false
      action_delay: 3
      predict: true
      target_update: soft
      dueling: true
      noisy: true
      distributional: false
      nstep: 3
    - run_group: nstep1_soft_noPred
      full_rewards: false
      action_delay: 3
      predict: false
      target_update: soft
      dueling: true
      noisy: true
      distributional: true
      nstep: 1
    - run_group: nstep1_soft_pred
      full_rewards: false
      action_delay: 3
      predict: true
      target_update: soft
      dueling: true
      noisy: true
      distributional: true
      nstep: 1
  environment:
    value: 8
  episode:
    value: 2500
  capacity:
    value: 140000
  updates:
    value: 2