program: sweep_train.py
method: grid
metric:
  name: episode/total_reward
  goal: maximize
parameters:
  combo:
    values:
    - run_group: d1_no_full_hard_pred_n3
      full_rewards: false
      action_delay: 1
      predict: true
      target_update: hard
      dueling: true
      noisy: true
      nstep: 3
    - run_group: d1_no_full_soft_pred_n1
      full_rewards: false
      action_delay: 1
      predict: true
      target_update: soft
      dueling: true
      noisy: true
      nstep: 3
  environment:
    value: 4
  episode:
    value: 5000
